services:
  mc-monitor:
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: host
    environment:
      CONFIG_PATH: /app/config.yaml
    volumes:
      - ./config.yaml:/app/config.yaml:ro
